### ISSUE TITLE
Add Tiny Panther logo?

### ISSUE THREAD

**Issue by datapolitan** [Datapolitan-Training/data-analysis-r#21]
@juliaem close this out if you don't want to throw it in

**Comment by datapolitan** [comment]
This image? 

![img](http://tinypanther.com/images/header.png)

**Comment by juliaem** [comment]
Let me give you a smaller one
![tinypanther_logo_compact_purple_600x400](https://cloud.githubusercontent.com/assets/10713940/21654846/55c7fb4c-d285-11e6-8251-bca879f810b8.png)

**Comment by juliaem** [comment]
Phase 2!
