### ISSUE TITLE
311_b ggplot fails

### ISSUE THREAD

**Issue by datapolitan** [Datapolitan-Training/data-analysis-r#55]
Error could not find function ggplot

With ggplot2::ggplot…
Error in aes(x =hour): could not find function "aes"

**Comment by datapolitan** [comment]
Have to do explicit cast using `ggplot2::`

**Comment by datapolitan** [comment]
Same with geom_bar. Doesn't plot correctly

**Comment by juliaem** [comment]
I don't know what this means.  Is this a problem with the code or with the install on DCAS computers?

**Comment by datapolitan** [comment]
I will load the RStudio on my Windows instance and check it out to see for sure

**Comment by datapolitan** [comment]
Not a problem with Windows. Maybe misconfigured on DCAS
